debug: true
device: cpu
seed: 123

wandb_args:
  project: ParisCensusTrOCR
  job_type: trOCR
  group: default
  mode: online

augment:
  augment: true
  aug_incr: 4

training_configs:
  epochs: 1
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  logging_steps: 2
  save_steps: 10000
  eval_steps: 1000
  report_to: none
  run_name: trOCR-Test
  target_path: ./model_tuned/

nlg_configs:
  max_length: 100
  early_stopping: True
  no_repeat_ngram_size: 3
  length_penalty: 1.0
  num_beams: 4